apiVersion: mxl.qvest-digital.com/v1alpha1
kind: MxlReceiver
metadata:
  name: rdma-demo
  namespace: mxl-system
spec:
  flowID: "5fbec3b1-1b0f-417d-9059-8b94a47197ed"
  provider: verbs
  podRef:
    name: mxl-rdma-demo-reader
    namespace: mxl-system
