// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/control.proto

package ipcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalControl_OpenMirror_FullMethodName         = "/mxl.k8s.ipc.v1.LocalControl/OpenMirror"
	LocalControl_CloseMirror_FullMethodName        = "/mxl.k8s.ipc.v1.LocalControl/CloseMirror"
	LocalControl_ListLocalEndpoints_FullMethodName = "/mxl.k8s.ipc.v1.LocalControl/ListLocalEndpoints"
)

// LocalControlClient is the client API for LocalControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalControl is served by the mxl-fabrics-gateway over a UDS
// (default /run/mxl/gateway.sock). The mxl-domain-agent is the only
// client. Cross-node gateway coordination happens through the
// Kubernetes API by way of MxlFlowMirror; there is no gateway-to-
// gateway gRPC surface in this version.
type LocalControlClient interface {
	// OpenMirror tells the gateway to materialize an incoming flow on
	// this node. The response carries the libmxl-fabrics target
	// descriptor (mxlFabricsTargetInfoToString) once the local target
	// is bound; the agent writes it into the MxlFlowMirror status so
	// the source-side gateway can attach its initiator.
	OpenMirror(ctx context.Context, in *OpenMirrorRequest, opts ...grpc.CallOption) (*OpenMirrorResponse, error)
	// CloseMirror tears down a mirror previously opened by OpenMirror.
	CloseMirror(ctx context.Context, in *CloseMirrorRequest, opts ...grpc.CallOption) (*CloseMirrorResponse, error)
	// ListLocalEndpoints reports the libmxl-fabrics endpoints currently
	// bound on this node.
	ListLocalEndpoints(ctx context.Context, in *ListLocalEndpointsRequest, opts ...grpc.CallOption) (*ListLocalEndpointsResponse, error)
}

type localControlClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalControlClient(cc grpc.ClientConnInterface) LocalControlClient {
	return &localControlClient{cc}
}

func (c *localControlClient) OpenMirror(ctx context.Context, in *OpenMirrorRequest, opts ...grpc.CallOption) (*OpenMirrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenMirrorResponse)
	err := c.cc.Invoke(ctx, LocalControl_OpenMirror_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localControlClient) CloseMirror(ctx context.Context, in *CloseMirrorRequest, opts ...grpc.CallOption) (*CloseMirrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseMirrorResponse)
	err := c.cc.Invoke(ctx, LocalControl_CloseMirror_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localControlClient) ListLocalEndpoints(ctx context.Context, in *ListLocalEndpointsRequest, opts ...grpc.CallOption) (*ListLocalEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocalEndpointsResponse)
	err := c.cc.Invoke(ctx, LocalControl_ListLocalEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalControlServer is the server API for LocalControl service.
// All implementations should embed UnimplementedLocalControlServer
// for forward compatibility.
//
// LocalControl is served by the mxl-fabrics-gateway over a UDS
// (default /run/mxl/gateway.sock). The mxl-domain-agent is the only
// client. Cross-node gateway coordination happens through the
// Kubernetes API by way of MxlFlowMirror; there is no gateway-to-
// gateway gRPC surface in this version.
type LocalControlServer interface {
	// OpenMirror tells the gateway to materialize an incoming flow on
	// this node. The response carries the libmxl-fabrics target
	// descriptor (mxlFabricsTargetInfoToString) once the local target
	// is bound; the agent writes it into the MxlFlowMirror status so
	// the source-side gateway can attach its initiator.
	OpenMirror(context.Context, *OpenMirrorRequest) (*OpenMirrorResponse, error)
	// CloseMirror tears down a mirror previously opened by OpenMirror.
	CloseMirror(context.Context, *CloseMirrorRequest) (*CloseMirrorResponse, error)
	// ListLocalEndpoints reports the libmxl-fabrics endpoints currently
	// bound on this node.
	ListLocalEndpoints(context.Context, *ListLocalEndpointsRequest) (*ListLocalEndpointsResponse, error)
}

// UnimplementedLocalControlServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalControlServer struct{}

func (UnimplementedLocalControlServer) OpenMirror(context.Context, *OpenMirrorRequest) (*OpenMirrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenMirror not implemented")
}
func (UnimplementedLocalControlServer) CloseMirror(context.Context, *CloseMirrorRequest) (*CloseMirrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseMirror not implemented")
}
func (UnimplementedLocalControlServer) ListLocalEndpoints(context.Context, *ListLocalEndpointsRequest) (*ListLocalEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocalEndpoints not implemented")
}
func (UnimplementedLocalControlServer) testEmbeddedByValue() {}

// UnsafeLocalControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalControlServer will
// result in compilation errors.
type UnsafeLocalControlServer interface {
	mustEmbedUnimplementedLocalControlServer()
}

func RegisterLocalControlServer(s grpc.ServiceRegistrar, srv LocalControlServer) {
	// If the following call pancis, it indicates UnimplementedLocalControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalControl_ServiceDesc, srv)
}

func _LocalControl_OpenMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenMirrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServer).OpenMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControl_OpenMirror_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServer).OpenMirror(ctx, req.(*OpenMirrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalControl_CloseMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseMirrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServer).CloseMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControl_CloseMirror_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServer).CloseMirror(ctx, req.(*CloseMirrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalControl_ListLocalEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocalEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalControlServer).ListLocalEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalControl_ListLocalEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalControlServer).ListLocalEndpoints(ctx, req.(*ListLocalEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalControl_ServiceDesc is the grpc.ServiceDesc for LocalControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mxl.k8s.ipc.v1.LocalControl",
	HandlerType: (*LocalControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenMirror",
			Handler:    _LocalControl_OpenMirror_Handler,
		},
		{
			MethodName: "CloseMirror",
			Handler:    _LocalControl_CloseMirror_Handler,
		},
		{
			MethodName: "ListLocalEndpoints",
			Handler:    _LocalControl_ListLocalEndpoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/control.proto",
}
