{{- if and .Values.agent.enabled .Values.agent.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-agent-metrics
  namespace: {{ include "mxlk8s.namespace" . }}
  labels:
    {{- include "mxlk8s.componentLabels" (dict "Context" . "component" "agent") | nindent 4 }}
spec:
  type: {{ .Values.agent.metrics.service.type }}
  clusterIP: None
  selector:
    {{- include "mxlk8s.selectorLabels" (dict "Context" . "component" "agent") | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.agent.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
