{{- if and .Values.gateway.enabled .Values.cleanup.preDeleteDomainWipe.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-predelete-domain-cleanup
  namespace: {{ include "mxlk8s.namespace" . }}
  labels:
    {{- include "mxlk8s.componentLabels" (dict "Context" . "component" "predelete-domain-cleanup") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed,before-hook-creation
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
