{{- if and .Values.agent.enabled .Values.agent.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-agent
  namespace: {{ include "mxlk8s.namespace" . }}
  labels:
    {{- include "mxlk8s.componentLabels" (dict "Context" . "component" "agent") | nindent 4 }}
    {{- with .Values.agent.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mxlk8s.selectorLabels" (dict "Context" . "component" "agent") | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.agent.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.agent.metrics.serviceMonitor.scrapeTimeout }}
      {{- with .Values.agent.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
