{{- if and .Values.gateway.enabled .Values.gateway.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mxlk8s.serviceAccountName" (dict "Context" . "component" "gateway" "values" .Values.gateway) }}
  namespace: {{ include "mxlk8s.namespace" . }}
  labels:
    {{- include "mxlk8s.componentLabels" (dict "Context" . "component" "gateway") | nindent 4 }}
    {{- with .Values.gateway.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.commonAnnotations .Values.gateway.serviceAccount.annotations }}
  annotations:
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.gateway.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gateway.serviceAccount.automountServiceAccountToken }}
{{- end }}
