//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorRef) DeepCopyInto(out *MirrorRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorRef.
func (in *MirrorRef) DeepCopy() *MirrorRef {
	if in == nil {
		return nil
	}
	out := new(MirrorRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlDomain) DeepCopyInto(out *MxlDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlDomain.
func (in *MxlDomain) DeepCopy() *MxlDomain {
	if in == nil {
		return nil
	}
	out := new(MxlDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlDomainList) DeepCopyInto(out *MxlDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MxlDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlDomainList.
func (in *MxlDomainList) DeepCopy() *MxlDomainList {
	if in == nil {
		return nil
	}
	out := new(MxlDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlDomainSpec) DeepCopyInto(out *MxlDomainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlDomainSpec.
func (in *MxlDomainSpec) DeepCopy() *MxlDomainSpec {
	if in == nil {
		return nil
	}
	out := new(MxlDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlDomainStatus) DeepCopyInto(out *MxlDomainStatus) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlDomainStatus.
func (in *MxlDomainStatus) DeepCopy() *MxlDomainStatus {
	if in == nil {
		return nil
	}
	out := new(MxlDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFabricsProviderCapability) DeepCopyInto(out *MxlFabricsProviderCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFabricsProviderCapability.
func (in *MxlFabricsProviderCapability) DeepCopy() *MxlFabricsProviderCapability {
	if in == nil {
		return nil
	}
	out := new(MxlFabricsProviderCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlow) DeepCopyInto(out *MxlFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlow.
func (in *MxlFlow) DeepCopy() *MxlFlow {
	if in == nil {
		return nil
	}
	out := new(MxlFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowList) DeepCopyInto(out *MxlFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MxlFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowList.
func (in *MxlFlowList) DeepCopy() *MxlFlowList {
	if in == nil {
		return nil
	}
	out := new(MxlFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowLocation) DeepCopyInto(out *MxlFlowLocation) {
	*out = *in
	if in.LastObserved != nil {
		in, out := &in.LastObserved, &out.LastObserved
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowLocation.
func (in *MxlFlowLocation) DeepCopy() *MxlFlowLocation {
	if in == nil {
		return nil
	}
	out := new(MxlFlowLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowMirror) DeepCopyInto(out *MxlFlowMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowMirror.
func (in *MxlFlowMirror) DeepCopy() *MxlFlowMirror {
	if in == nil {
		return nil
	}
	out := new(MxlFlowMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlFlowMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowMirrorList) DeepCopyInto(out *MxlFlowMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MxlFlowMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowMirrorList.
func (in *MxlFlowMirrorList) DeepCopy() *MxlFlowMirrorList {
	if in == nil {
		return nil
	}
	out := new(MxlFlowMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlFlowMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowMirrorSpec) DeepCopyInto(out *MxlFlowMirrorSpec) {
	*out = *in
	if in.Requestor != nil {
		in, out := &in.Requestor, &out.Requestor
		*out = new(PodRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowMirrorSpec.
func (in *MxlFlowMirrorSpec) DeepCopy() *MxlFlowMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(MxlFlowMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowMirrorStatus) DeepCopyInto(out *MxlFlowMirrorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowMirrorStatus.
func (in *MxlFlowMirrorStatus) DeepCopy() *MxlFlowMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(MxlFlowMirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowSpec) DeepCopyInto(out *MxlFlowSpec) {
	*out = *in
	in.Definition.DeepCopyInto(&out.Definition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowSpec.
func (in *MxlFlowSpec) DeepCopy() *MxlFlowSpec {
	if in == nil {
		return nil
	}
	out := new(MxlFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlFlowStatus) DeepCopyInto(out *MxlFlowStatus) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]MxlFlowLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlFlowStatus.
func (in *MxlFlowStatus) DeepCopy() *MxlFlowStatus {
	if in == nil {
		return nil
	}
	out := new(MxlFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlNodeCapabilities) DeepCopyInto(out *MxlNodeCapabilities) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlNodeCapabilities.
func (in *MxlNodeCapabilities) DeepCopy() *MxlNodeCapabilities {
	if in == nil {
		return nil
	}
	out := new(MxlNodeCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlNodeCapabilities) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlNodeCapabilitiesList) DeepCopyInto(out *MxlNodeCapabilitiesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MxlNodeCapabilities, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlNodeCapabilitiesList.
func (in *MxlNodeCapabilitiesList) DeepCopy() *MxlNodeCapabilitiesList {
	if in == nil {
		return nil
	}
	out := new(MxlNodeCapabilitiesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlNodeCapabilitiesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlNodeCapabilitiesSpec) DeepCopyInto(out *MxlNodeCapabilitiesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlNodeCapabilitiesSpec.
func (in *MxlNodeCapabilitiesSpec) DeepCopy() *MxlNodeCapabilitiesSpec {
	if in == nil {
		return nil
	}
	out := new(MxlNodeCapabilitiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlNodeCapabilitiesStatus) DeepCopyInto(out *MxlNodeCapabilitiesStatus) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]MxlFabricsProviderCapability, len(*in))
		copy(*out, *in)
	}
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlNodeCapabilitiesStatus.
func (in *MxlNodeCapabilitiesStatus) DeepCopy() *MxlNodeCapabilitiesStatus {
	if in == nil {
		return nil
	}
	out := new(MxlNodeCapabilitiesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlReceiver) DeepCopyInto(out *MxlReceiver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlReceiver.
func (in *MxlReceiver) DeepCopy() *MxlReceiver {
	if in == nil {
		return nil
	}
	out := new(MxlReceiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlReceiver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlReceiverList) DeepCopyInto(out *MxlReceiverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MxlReceiver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlReceiverList.
func (in *MxlReceiverList) DeepCopy() *MxlReceiverList {
	if in == nil {
		return nil
	}
	out := new(MxlReceiverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MxlReceiverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlReceiverSpec) DeepCopyInto(out *MxlReceiverSpec) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(PodRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlReceiverSpec.
func (in *MxlReceiverSpec) DeepCopy() *MxlReceiverSpec {
	if in == nil {
		return nil
	}
	out := new(MxlReceiverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MxlReceiverStatus) DeepCopyInto(out *MxlReceiverStatus) {
	*out = *in
	if in.BoundMirror != nil {
		in, out := &in.BoundMirror, &out.BoundMirror
		*out = new(MirrorRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MxlReceiverStatus.
func (in *MxlReceiverStatus) DeepCopy() *MxlReceiverStatus {
	if in == nil {
		return nil
	}
	out := new(MxlReceiverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRef) DeepCopyInto(out *PodRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRef.
func (in *PodRef) DeepCopy() *PodRef {
	if in == nil {
		return nil
	}
	out := new(PodRef)
	in.DeepCopyInto(out)
	return out
}
