apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxl-operator
  namespace: mxl-system
  labels:
    app.kubernetes.io/name: mxl-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mxl-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mxl-operator
    spec:
      serviceAccountName: mxl-operator
      containers:
        - name: operator
          image: ghcr.io/qvest-digital/mxl-k8s/operator:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: probe
              containerPort: 8081
            - name: metrics
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
